<template>
  <div class="field">
    <label
      :class="{ required: required && config.label }"
      :for="config.id || autoGeneratedId"
      v-if="config.label"
    >
      {{ config.label }}
    </label>
    <label :for="config.id || autoGeneratedId">&nbsp;</label>
    <Password
      :id="config.id || autoGeneratedId"
      :placeholder="config.placeholder"
      :disabled="config.disabled"
      :class="{
        'p-inputtext-sm': config.size === 'sm',
        'p-inputtext-lg': config.size === 'lg',
        'p-inputtext-filled': config.filled,
        'p-invalid': v.$invalid,
      }"
      :strongRegex="strongRegex"
      :mediumRegex="mediumRegex"
      :toggleMask="allowReveal"
      :feedback="allowFeedback"
      v-model="v.$model"
      class="w-full"
    >
      <template #header v-if="allowFeedback">
        <h6>{{ feedbackTitle }}</h6>
      </template>
      <template #footer v-if="allowFeedback">
        <Divider />
        <p class="mt-2">{{ feedbackSubtitle }}</p>
        <ul class="pl-2 ml-2 mt-0" style="line-height: 1.5">
          <li v-for="guideline in feedbackGuidelines" :key="guideline">
            {{ guideline }}
          </li>
        </ul>
      </template>
    </Password>
    <small class="block" :class="{ 'p-error': v.$invalid }">{{
      v.$errors.length
        ? v[v.$errors[0].$validator].$message.replace("Value", config.helpName)
        : config.helpText || ""
    }}</small>
  </div>
</template>
<script>
import { ref, toRef } from "@vue/reactivity";

export default {
  name: "CustomInputText",
  props: {
    config: {
      type: Object,
      required: true,
    },

    validator: Object,

    required: Boolean,
  },
  setup(props) {
    const config = toRef(props, "config");
    const model = toRef(config.value, "model");
    const autoGeneratedId = ref(`${Date.now()}`);
    const name = toRef(config.value, "name");
    const strongRegex = ref(
      config.value.strongRegex || /^(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.{8,})/
    );
    const mediumRegex = ref(
      config.value.mediumRegex || /^(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.{8,})/
    );
    const allowReveal = ref(config.value.allowReveal || false);
    const allowFeedback = ref(config.value.allowFeedback || false);
    const feedbackTitle = ref(config.value.feedbackTitle || "Password guide");
    const feedbackSubtitle = ref(
      config.value.feedbackSubtitle || "Suggestions"
    );
    const feedbackGuidelines = ref(
      config.value.feedbackGuidelines || [
        "At least one lowercase",
        "At least one uppercase",
        "At least one numeric",
        "Minimum 8 characters",
      ]
    );
    const v = toRef(props, "validator");

    return {
      model,
      autoGeneratedId,
      name,
      v,
      strongRegex,
      mediumRegex,
      allowReveal,
      allowFeedback,
      feedbackTitle,
      feedbackSubtitle,
      feedbackGuidelines,
    };
  },
};
</script>