<template>
  <div class="field">
    <label
      :class="{ required: required && config.label }"
      :for="config.id || autoGeneratedId"
      v-if="config.label"
    >
      {{ config.label }}
    </label>
    <label :for="config.id || autoGeneratedId">&nbsp;</label>
    <InputText
      :id="config.id || autoGeneratedId"
      :placeholder="config.placeholder"
      :disabled="config.disabled"
      :class="{
        'p-inputtext-sm': config.size === 'sm',
        'p-inputtext-lg': config.size === 'lg',
        'p-inputtext-filled': config.filled,
        'p-invalid': v.$invalid && v.$dirty,
      }"
      class="w-full"
      v-model="v.$model"
      @input="onInput"
    ></InputText>
    <small class="block" :class="{ 'p-error': v.$invalid && v.$dirty }">{{
      v.$errors.length
        ? v[v.$errors[0].$validator].$message.replace("Value", config.helpName)
        : config.helpText || ""
    }}</small>
  </div>
</template>
<script>
import { ref, toRef } from "@vue/reactivity";

export default {
  name: "CustomInputText",
  props: {
    config: {
      type: Object,
      required: true,
    },

    validator: Object,

    // True if the field is required
    required: Boolean,
  },
  setup(props) {
    const config = toRef(props, "config");
    const model = toRef(config.value, "model");
    const autoGeneratedId = ref(`${Date.now()}`);
    const name = toRef(config.value, "name");
    const v = toRef(props, "validator");

    const onInput = ({ target: { value } }) => {
      console.log({ value });
      // config.value?.onInput({ [name.value]: value });
    };

    return { model, autoGeneratedId, name, onInput, v };
  },
};
</script>