<template>
  <div class="field">
    <label
      :class="{ required: required && config.label }"
      :for="config.id || autoGeneratedId"
      v-if="config.label"
    >
      {{ config.label }}
    </label>
    <label :for="config.id || autoGeneratedId">&nbsp;</label>
    <Dropdown
      :id="config.id || autoGeneratedId"
      :placeholder="config.placeholder"
      :disabled="config.disabled"
      :class="{
        'p-inputtext-sm': config.size === 'sm',
        'p-inputtext-lg': config.size === 'lg',
        'p-inputtext-filled': config.filled,
        'p-invalid': v.$invalid && v.$dirty,
      }"
      v-model="v.$model"
      class="w-full"
      :options="options"
      :optionLabel="config.optionLabel"
      :optionGroupLabel="config.optionGroupLabel"
      :optionGroupChildren="config.optionGroupChildren"
      :filter="config.filter"
      :filterPlaceholder="config.filterPlaceholder"
      :emptyMessage="config.emptyMessage"
      :loading="config.loading"
      @change="onChange"
    ></Dropdown>
    <small class="block" :class="{ 'p-error': v.$invalid }">{{
      v.$errors.length
        ? v[v.$errors[0].$validator].$message.replace("Value", config.helpName)
        : config.helpText || ""
    }}</small>
  </div>
</template>
<script>
import { ref, toRef } from "@vue/reactivity";

export default {
  name: "CustomInputText",
  props: {
    config: {
      type: Object,
      required: true,
    },

    validator: Object,

    required: Boolean,
  },
  setup(props) {
    const config = toRef(props, "config");
    const autoGeneratedId = ref(`${Date.now()}`);
    const name = toRef(config.value, "name");
    const options = toRef(config.value, "options");
    const onChange = toRef(config.value, "onChange");
    const v = toRef(props, "validator");

    return { autoGeneratedId, v, name, options, onChange };
  },
};
</script>